### ISSUE TITLE
New Yarg dependency adds `site-packages/tests` directory

### ISSUE THREAD

**Issue by whoffler** [PyCQA/isort#2209] opened 2023-12-11 11:07 UTC
new version `1.5.3` installs `yarg` package as dependency

yarg package adds `site-packages/tests` directory when installed

Attempts to import from our own projects `tests` directory fail as the  python interpreter tries to import from `site-packages/tests` instead

we have pinned to version `1.5.2`

**Comment by miketheman** [comment] 2023-12-11 16:39
Duplicate of https://github.com/PyCQA/isort/issues/2206

**Comment by staticdev** [comment] 2023-12-11 20:14
Could you please check @whoffler if it happens on 5.13.1?

**Comment by staticdev** [comment] 2023-12-13 21:02
Ok I will consider this closed then, if it continues please reopen.

**Closed by staticdev** 2023-12-13 21:02 UTC

**Comment by whoffler** [comment] 2023-12-14 09:22
> Could you please check @whoffler if it happens on 5.13.2?

Not seeing issue anymore. Thanks
