### ISSUE TITLE
ERROR: Unrecoverable exception thrown when parsing tests/fixtures/__init__.py!This should NEVER happen.

### ISSUE THREAD

**Issue by A143865** [PyCQA/isort#1807] opened 2021-09-10 15:13 UTC
Traceback (most recent call last):
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/lib/python3.9/site-packages/isort/main.py", line 1185, in main
    for sort_attempt in attempt_iterator:
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/lib/python3.9/site-packages/isort/main.py", line 1170, in <genexpr>
    sort_imports(  # type: ignore
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/lib/python3.9/site-packages/isort/main.py", line 92, in sort_imports
    incorrectly_sorted = not api.sort_file(
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/lib/python3.9/site-packages/isort/api.py", line 407, in sort_file
    changed = sort_stream(
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/lib/python3.9/site-packages/isort/api.py", line 210, in sort_stream
    changed = core.process(
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/lib/python3.9/site-packages/isort/core.py", line 384, in process
    parsed_content = parse.file_contents(import_section, config=config)
  File "/Users/a143865/.cache/pre-commit/reposrxo0one/py_env-python3/lib/python3.9/site-packages/isort/parse.py", line 450, in file_contents
    root = imports[placed_module][type_of_import]  # type: ignore
KeyError: 'LOCALFOLDER'

**Comment by anirudnits** [comment] 2021-09-10 18:04
Hello @A143865, can you share the isort configurations you are using? You can fetch them by running `isort . --show-config`.

**Comment by A143865** [comment] 2021-09-13 14:00
> Hello @A143865, can you share the isort configurations you are using? You can fetch them by running `isort . --show-config`.

Certainly. I should also note that this error did resolve though it did so without any effort from me to try and debug. 
[isort_configs.txt](https://github.com/PyCQA/isort/files/7154799/isort_configs.txt)

**Comment by anirudnits** [comment] 2021-09-14 05:11
Thanks @A143865. On first glance, I see that in the "sections" config, you didn't include "LOCALFOLDER" and this might have caused the issue. Can you also confirm the isort version you are using? because in the recent versions, the error is handled and a more informative error message is printed: https://github.com/PyCQA/isort/blob/4ccbd1eddf564d2c9e79c59d59c1fc06a7e35f94/isort/parse.py#L561.

**Comment by anirudnits** [comment] 2021-09-14 05:47
I found the cause of the error message being directly printed on the console, so the `MissingSections` exception was properly handled for this one case and so the error wasn't handled. With this, I hope it would be simpler to debug such errors.

~ Aniruddha

**Comment by A143865** [comment] 2021-09-15 10:40
> Thanks @A143865. On first glance, I see that in the "sections" config, you didn't include "LOCALFOLDER" and this might have caused the issue. Can you also confirm the isort version you are using? because in the recent versions, the error is handled and a more informative error message is printed:
> 

I have isort=5.9.3, which I see is the latest version. I have added "LOCALFOLDER" in the config sections; hopefully this will correct any future problem on my end.

**Comment by anirudnits** [comment] 2021-09-15 10:50
@A143865 yeah adding "LOCALFOLDER" in sections should do the trick. The PR has been merged and with the new release, whenever that is, a more informative error message will be printed to help guide people to understand and resolve the issue more quickly.

**Closed by anirudnits** 2021-09-15 10:50 UTC
