### ISSUE TITLE
Possible bug when length of line is exactly line_length under certain conditions

### ISSUE THREAD

**Issue by mhiley** [PyCQA/isort#1634] opened 2021-01-08 16:18 UTC
Hello, I think there may be a bug where under certain conditions, isort wants to wrap an import line with a length that is exactly equal to `line_length`.

Example (`line_length` is set to 100, `wrap_length` not set):

When I have an import of this form that's exactly 100 characters long:
```python
from a import aaaaaaaaaaa, bbbbbbbbbbbb, cccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeee
```
then isort leaves it alone.

However, when I have an import of this form, where the longer line is exactly 100 characters long:
```python
from a import (
    aaaaaaaaaaa, bbbbbbbbbbbb, cccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeeeeee
)
```
...then isort wants to wrap the last import (`eeeeeeeeeeeeeeeeeeeeeeeeeeeeee`) onto the next line.

This seems like a bug to me, or am I interpreting the exact meaning of `line_length` incorrectly? Thank you!

Here is my full `.isort.cfg`:
```
[settings]
atomic=1
indent=4
use_parentheses=1
line_length=100
lines_between_types=0
multi_line_output=5
no_sections=1
from_first=1
```

**Comment by gofr** [comment] 2021-01-09 17:25
The bug happens here:
https://github.com/PyCQA/isort/blob/98fad1127fc0771959ab39303548e3b50a1e7b5f/isort/wrap_modes.py#L204

I think there's a bit of a mismatch between what the two "vert-grid-grouped" multi-line wrapping modes sound like they should do and what they actually do.

Given the name of mode 6-vert-grid-grouped-no-comma, mode 5-vert-grid-grouped sounds like it includes a trailing comma on the last line while mode 6 doesn't. But neither of them control commas at all. The `include_trailing_comma` option does.

In this case what happens is that mode 5 makes sure there's room for the comma, but then doesn't actually add that comma. 

If instead you use `multi_line_output=6`, but also set `include_trailing_comma=1` you get the opposite wrong behavior: A trailing comma is included but the line is not wrapped, creating a line of 101 characters even though the line length is 100.

Two potential ways of fixing this I can think of:
* Merge modes 5 and 6, dropping one of them or making them aliases. Let `include_trailing_comma` control the comma.
* Make the 5-vert-grid-grouped mode implicitly set/override `include_trailing_comma` to `True`, and make mode 6 override it to `False`.

**Comment by gofr** [comment] 2021-01-09 18:03
mode 4-vert-grid is also affected. If that mode is combined with `include_trailing_comma=1`, there will be _two_ trailing characters (comma and closing parenthesis), but the code only makes enough room for one character.

**Comment by gofr** [comment] 2021-01-09 18:40
Oh, I finally found the documentation for the modes, which sort of describes this edge case:
https://pycqa.github.io/isort/#multi-line-output-modes

So not entirely sure now if this is working as intended.

**Comment by timothycrosley** [comment] 2021-01-17 00:43
@gofr, I think your spot on in your analysis and this is indeed intended behavior

**Closed by timothycrosley** 2021-01-17 00:43 UTC
