### ISSUE TITLE
AttributeError: type object 'File' has no attribute 'read'

### ISSUE THREAD

**Issue by nirutgupta** [PyCQA/isort#1608] opened 2020-12-14 20:16 UTC
isort failing for the version 5.6.4

ERROR: Unrecoverable exception thrown when parsing qaas_liftie/cli/core.py! This should NEVER happen.
If encountered, please open an issue: https://github.com/PyCQA/isort/issues/new
Traceback (most recent call last):
  File "/Users/nirut.gupta/workspace/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/Users/nirut.gupta/workspace/lib/python3.6/site-packages/isort/main.py", line 953, in main
    for sort_attempt in attempt_iterator:
  File "/Users/nirut.gupta/workspace/lib/python3.6/site-packages/isort/main.py", line 947, in <genexpr>
    for file_name in file_names
  File "/Users/nirut.gupta/workspace/lib/python3.6/site-packages/isort/main.py", line 100, in sort_imports
    **kwargs,
  File "/Users/nirut.gupta/workspace/lib/python3.6/site-packages/isort/api.py", line 303, in sort_file
    with io.File.read(filename) as source_file:
AttributeError: type object 'File' has no attribute 'read'

Steps to reproduce:
I think any file or directory will work 
isort myfile/or/directory

**Comment by nirutgupta** [comment] 2020-12-14 20:20
Ok i think its not the isort version but its the python version that is causing problem. Tried 5.5.0 version as well against python 3.6.0 still the same result.

**Comment by timothycrosley** [comment] 2020-12-30 21:31
This is a duplicate of: https://github.com/PyCQA/isort/issues/1593 which is fixed in isort development branch and awaiting release by end of month. More details are on the linked ticket, but the TLDR is that it's caused by a bug in Python 3.6.0 - which has been fixed in Python itself within the 3.6 series so isn't caught by isort's CI/CD which can't reasonably test against all minor releases of Python

**Closed by timothycrosley** 2020-12-30 21:31 UTC
Labels: duplicate
